name: CustomWeapons
version: @version@
main: de.untrusteduser.customweapons.CustomWeapons
api-version: 1.16
authors: [UntrustedUser]
description: Adds a bunch of different weapons to minecraft
website: https://github.com/UntrustedUser