name: CustomWeapons
version: 1.0.0
main: de.tosoxdev.customweapons.CustomWeapons
api-version: 1.16
authors: [TosoxDev]
description: Adds a bunch of different weapons to minecraft
website: https://github.com/TosoxDev

commands:
  cwg:
    description: Gives you the custom weapon of your choice